<?php

namespace Blogger\WallBundle\Repository;

/**
 * WallPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallPostRepository extends \Doctrine\ORM\EntityRepository
{
}
