blogger_blog_topic_game:
    channel: app/chat/{room}/{user_id}
    handler:
        callback: 'topic.game' #Относится к getName, а не к имени сервиса
    requirements:
        room:
            pattern: "[a-z]+" #accept all valid regex, don't put delimiters !
        user_id:
            pattern: "\d+"