blogger_map_marker:
    resource: "@BloggerMapBundle/Controller/MarkerController.php"
    type:     annotation

blogger_map:
    resource: "@BloggerMapBundle/Resources/config/routing.yml"
    prefix:   /

blogger_tasklist:
    resource: "@BloggerTodolistBundle/Controller/"
    type:     annotation
    prefix:   /

blogger_blog_user:
    resource: "@BloggerBlogBundle/Controller/UserController.php"
    type:     annotation

blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    