blogger_blog_post:
    resource: "@BloggerBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET

about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET

show:
    path:  /posts/{id}
    defaults: { _controller: "BloggerBlogBundle:Post:view" }
    requirements:
        methods:  GET
        id: \d+

all_posts:
    path:  /post
    defaults: { _controller: "BloggerBlogBundle:Post:index" }
    requirements:
        methods:  GET
