homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET

about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET

show:
    path:  /{id}
    defaults: { _controller: "BloggerBlogBundle:Post:show" }
    requirements:
        methods:  GET
        id: \d+