
services:
    blogger.blog.topic.game:
        class: Blogger\BlogBundle\Topic\GameTopic
        arguments: 
          - @doctrine.orm.default_entity_manager
          - @gos_web_socket.websocket.client_manipulator
        tags:
          - { name: gos_web_socket.topic }
