<?php

namespace Blogger\MapBundle\Repository;

/**
 * MapResolverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapResolverRepository extends \Doctrine\ORM\EntityRepository
{
}
