
services:
    blogger.blog.topic.chat:
        class: Blogger\ChatBundle\Topic\ChatTopic
        arguments: 
          - @doctrine.orm.default_entity_manager
          - @gos_web_socket.websocket.client_manipulator
        tags:
          - { name: gos_web_socket.topic }
